### ISSUE TITLE
Polygonal a href

### ISSUE THREAD

**Issue by lemonsaurus** [lymmers/goose_pond#13]
We want to only be able to click the goose _exactly on the shape of the goose_, not in the empty space _around_ the goose. That sucks.

The way to solve this would be to put the link _[inside the svg for the image](https://stackoverflow.com/questions/1778589/non-rectangular-css-image-links)_.

For example:
```html
<svg height="210" width="500" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
  <a xlink:href="https://stackoverflow.com/">
    <polygon points="200,10 250,190 160,210" style="fill:blue;stroke:black;stroke-width:2" />
  </a>
</svg>
```

**Comment by lymmers** [comment]
Resolved
